# Add application configuration variables here, as shown below.
#

GMAIL_USERNAME: gmailusername
GMAIL_PASSWORD: gmailpass
ADMIN_FIRST_NAME: Morshed
ADMIN_LAST_NAME: Alam
ADMIN_EMAIL: morshed@nsbench.com
ADMIN_PASSWORD: morshed
USER_FIRST_NAME: user
USER_EMAIL: user@nsbench.com
USER_PASSWORD: userpass
ROLES: [admin, user]